name: flutter_playground
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffi: ^1.0.0
  bot_toast: ^4.0.1
  freezed_annotation: ^0.14.3
  flutter_bloc: 7.2.0
  dio: ^4.0.0
  json_annotation: ^4.1.0
  intl: ^0.17.0
  rxdart: ^0.27.1
  presentation: ^1.0.0
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  build_runner: 2.1.1


dependency_overrides:
  meta: 1.7.0
  analyzer: 2.1.0
  characters: 1.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

